defaultProject: bigquery-test-march
defaultLocation: australia-southeast1
defaultDataset: pirlo_calligraphy_s
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.52
vars:
  GA4_DATASET: pirlo_calligraphy_s
  LOCAL_TIMEZONE: Australia/Adelaide
  OUTPUTS_DATASET: pirlo_calligraphy
  TRANSFORMATION_DATASET: pirlo_calligraphy_i