defaultProject: bigquery-test-march
defaultLocation: asia-southeast2
defaultDataset: pirlo_calligraphy
defaultAssertionDataset: dataform_assertions_asia
dataformCoreVersion: 3.0.52
vars:
  GA4_DATASET: analytics_454895025
  LOCAL_TIMEZONE: Australia/Adelaide
  OUTPUTS_DATASET: pirlo_calligraphy
  TRANSFORMATION_DATASET: pirlo_calligraphy_i
