config {
    type: "incremental",
    description: "This output event table are ready for Data Studio which is unnested, cleaned, clustered data with several fixes",
    schema: dataform.projectConfig.vars.OUTPUTS_DATASET,
    bigquery: {
        partitionBy: "event_date",
        clusterBy: ["event_date", "session_id"]
    },
    columns: require("includes/core/documentation/helpers.js").ga4Events
}

js{
    // It returns the whole js file and needs to find and match helpers object
    const {helpers} = require("includes/core/modules/ga4/helpers.js");
    // It returns the object already so just needs a variable to refer to
    const config = helpers.getModuleConfig("ga4");
    // check if there is invalid columns or duplicate columns in the custom config
    helpers.checkColumnNames(config);
}

pre_operations {
    DECLARE date_checkpoint DATE;
    SET date_checkpoint = {
        ${when(incremental(),
            `SELECT COALESCE(MAX(event_date)+1, DATE('${config.GA4_START_DATE}')) from ${self()}
            where is_final=true`,
            `SELECT DATE('${config.GA4_START_DATE}')`)
        }
    };

    ${when(incremental(),
        `DELETE FROM ${self()} WHERE event_date >= date_checkpoint`)}
}

WITH source_ga4_export AS (
    SELECT
        *,
        _table_suffix as table_suffix,
    FROM ${ref("events_*")}
    WHERE
        PARSE_DATE('%Y%m%d', REGEXP_EXTRACT(_table_suffix, '[0-9]+')) >= date_checkpoint
    AND 
    -- Exclude the events_intraday_* tables
        CONTAINS_SUBSTR(_table_suffix, 'intraday') IS FALSE
    AND
    -- Exclude the events_fresh_* tables
        CONTAINS_SUBSTR(_table_suffix, 'fresh') IS FALSE
    AND
    -- Exclude the unwanted events defined in config.js
        ${helpers.generateFilterTypeFromListSQL("exclude", "events_name", config.EVENTS_TO_EXCLUDE)}
    AND
    -- Exclude the unwanted hostsnames, like localhost
        ${helpers.generateFilterTypeFromListSQL("exclude", "device.web_info.hostname", config.HOSTNAME_EXCLUDE)}
    AND
    -- Include the wanted hostsnames
        ${helpers.generateFilterTypeFromListSQL("include", "device.web_info.hostname", config.HOSTNAME_INCLUDE_ONLY)}
),

stage_unnest_params as (
    SELECT
        event_name,
        table_suffix,
        PARSE_DATE('%Y%m%d', event_date) as event_date, -- partition column
        -- used for incrementality
        DATE_DIFF(CURRENT_DATE(), CAST(event_date AS DATE FORMAT 'YYYMMDD'), DAY) > $(config.DATE_IS_FUNAL_DAYS) as is_final,

        STRUCT(
            event_timestamp,
            -- Transfer to timestamp type
            TIMESTAMP_MICROS(event_timestamp) AS event_timestamp_utc,
            user_first_touch_timestamp as user_first_touch_timestamp,
            TIMESTAPM_MICROS(user_first_touch_timestamp) as user_first_touch_timestamp_utc
        ) AS time,

        -- User info
        user_pseudo_id,
        user_id,
        is_active_user,

        -- Event info
        batch_event_index,
        batch_ordering_id,
        batch_page_id,

        -- All the following fields needs to be listed here in order not be broen when Google adds new
        -- fields in the future
        STRUCT(
            privacy_info.analytics_storage AS analytics_storage,
            privacy_info.ads_storage AS ads_storage,
            privacy_info.uses_transient_token AS uses_transient_token
        ) AS privacy_info,

        STRUCT(
            collected_traffic_source.manual_campaign_id,
            collected_traffic_source.manual_campaign_name,
            collected_traffic_source.manual_source,
            collected_traffic_source.manual_medium,
            collected_traffic_source.manual_term,
            collected_traffic_source.manual_content,
            collected_traffic_source.manual_source_platform,
            collected_traffic_source.manual_creative_format,
            collected_traffic_source.manual_marketing_tactic,
            collected_traffic_source.gclid,
            collected_traffic_source.dclid,
            collected_traffic_source.stsltid
        ) AS coolected_traffic_source,

        STRUCT(
            STRUCT(
                session_traffic_source_last_click.manual_campaign.campaign_id,
                session_traffic_source_last_click.manual_campaign.campaign_name,
                session_traffic_source_last_click.manual_campaign.source,
                session_traffic_source_last_click.manual_campaign.medium,
                session_traffic_source_last_click.manual_campaign.term,
                session_traffic_source_last_click.manual_campaign.content,
                session_traffic_source_last_click.manual_campaign.source_platform,
                session_traffic_source_last_click.manual_campaign.creative_format,
                session_traffic_source_last_click.manual_campaign.marketing_tactic
            ) AS manual_campaign,

            STRUCT(
                session_traffic_source_last_click.google_ads_campaign.customer_id,
                session_traffic_source_last_click.google_ads_campaign.account_name,
                session_traffic_source_last_click.google_ads_campaign.campaign_id,
                session_traffic_source_last_click.google_ads_campaign.campaign_name,
                session_traffic_source_last_click.google_ads_campaign.ad_group_id,
                session_traffic_source_last_click.google_ads_campaign.ad_group_name
            ) AS google_ads_campaign,

            STRUCT(
                session_traffic_source_last_click.cross_channel_campaign.campaign_id,
                session_traffic_source_last_click.cross_channel_campaign.campaign_name,
                session_traffic_source_last_click.cross_channel_campaign.source,
                session_traffic_source_last_click.cross_channel_campaign.medium,
                session_traffic_source_last_click.cross_channel_campaign.source_platform,
                session_traffic_source_last_click.cross_channel_campaign.default_channel_group,
                session_traffic_source_last_click.cross_channel_campaign.primary_channel_group
            ) AS cross_channel_campaign,

            STRUCT(
                session_traffic_source_last_click.sa360_campaign.campaign_id,
                session_traffic_source_last_click.sa360_campaign.campaign_name,
                session_traffic_source_last_click.sa360_campaign.source,
                session_traffic_source_last_click.sa360_campaign.medium,
                session_traffic_source_last_click.sa360_campaign.ad_group_id,
                session_traffic_source_last_click.sa360_campaign.ad_group_name,
                session_traffic_source_last_click.sa360_campaign.creative_format,
                session_traffic_source_last_click.sa360_campaign.engine_account_name,
                session_traffic_source_last_click.sa360_campaign.enging_account_type,
                session_traffic_source_last_click.sa360_campaign.manager_account_name
            ) AS sa360_campaign,

            STRUCT(
                session_traffic_source_last_click.cm360_campaign.campaign_id,
                session_traffic_source_last_click.cm360_campaign.campaign_name,
                session_traffic_source_last_click.cm360_campaign.source,
                session_traffic_source_last_click.cm360_campaign.medium,
                session_traffic_source_last_click.cm360_campaign.account_id,
                session_traffic_source_last_click.cm360_campaign.account_name,
                session_traffic_source_last_click.cm360_campaign.advertiser_id,
                session_traffic_source_last_click.cm360_campaign.advertiser_name,
                session_traffic_source_last_click.cm360_campaign.creative_id,
                session_traffic_source_last_click.cm360_campaign.creative_format,
                session_traffic_source_last_click.cm360_campaign.creative_name,
                session_traffic_source_last_click.cm360_campaign.creative_type,
                session_traffic_source_last_click.cm360_campaign.creative_type_id,
                session_traffic_source_last_click.cm360_campaign.creative_version,
                session_traffic_source_last_click.cm360_campaign.placement_id,
                session_traffic_source_last_click.cm360_campaign.placement_cost_structure,
                session_traffic_source_last_click.cm360_campaign.placement_name,
                session_traffic_source_last_click.cm360_campaign.rendering_id,
                session_traffic_source_last_click.cm360_campaign.site_id,
                session_traffic_source_last_click.cm360_campaign.site_name
            ) AS cm360_campaign,

            STRUCT(
                session_traffic_source_last_click.dv360_campaign.campaign_id,
                session_traffic_source_last_click.dv360_campaign.campaign_name,
                session_traffic_source_last_click.dv360_campaign.source,
                session_traffic_source_last_click.dv360_campaign.medium,
                session_traffic_source_last_click.dv360_campaign.advertiser_id,
                session_traffic_source_last_click.dv360_campaign.advertiser_name,
                session_traffic_source_last_click.dv360_campaign.creative_id,
                session_traffic_source_last_click.dv360_campaign.creative_format,
                session_traffic_source_last_click.dv360_campaign.creative_name,
                session_traffic_source_last_click.dv360_campaign.exchange_id,
                session_traffic_source_last_click.dv360_campaign.exchange_name,
                session_traffic_source_last_click.dv360_campaign.insertion_order_id,
                session_traffic_source_last_click.dv360_campaign.insertion_order_name,
                session_traffic_source_last_click.dv360_campaign.line_item_id,
                session_traffic_source_last_click.dv360_campaign.line_item_name,
                session_traffic_source_last_click.dv360_campaign.partner_id,
                session_traffic_source_last_click.dv360_campaign.partner_name
            ) AS dv360_campaign
        ) AS session_traffic_source_last_click,

        STRUCT(
            publisher.ad_revenue_in_usd,
            publisher.ad_format,
            publisher.ad_source_name,
            publisher.ad_unit_id
        ) AS publisher,

        ecommerce, -- This will be repacked and cleaned later in step 2

        STRUCT(
            user_ltv.revenue,
            user_ltv.currency
        ) AS user_ltv,

        STRUCT(
            device.category,
            device.mobile_brand_name,
            device.mobile_model_name,
            device.mobile_marketing_name,
            device.mobile_os_hardware_model,
            device.operating_system,
            device.operating_system_version,
            device.vendor_id,
            device.advertising_id,
            device.language,
            device.is_limited_ad_tracking,
            device.time_zone_offset_seconds,
            device.browser,
            device.browser_version,
            STRUCT(
                device.web_info.browser,
                device.web_info.browser_version,
                device.web_info.hostname
            ) AS web_info
        ) AS device,

        STRUCT(
            app_info.id,
            app_info.version,
            app_info.install_store,
            app_info.firebase_app_id,
            app_info.install_source
        ) AS app_info,

        STRUCT(
            geo.city,
            geo.country,
            geo.continent,
            geo.region,
            geo.sub_continent,
            geo.metro
        ) AS geo,

        STRUCT(
            traffic_source.name AS campaign_name,
            traffic_source.medium,
            traffic_source.source
        ) AS first_user_traffic_source,

        stream_id,
        platform,
        '${dataform.projectConfig.vars.GA4_DATASET}' AS property_id,

        -- Repack this array of struct in order to insert a custom field item_params_custom
        -- Custom item property may look like this:
        -- ({name: 'color', type: 'string'}, {name: 'discount', type: 'double'})
        -- where name in key field, type in value field
        ARRAY(
            (
            SELECT
                STRUCT(
                    items.item_id,
                    items.item_name,
                    items.item_brand,
                    items.item_variant,
                    items.item_category,
                    items.item_category2,
                    items.item_category3,
                    items.item_category4,
                    items.item_category5,
                    items.price_in_usd,
                    items.price,
                    items.quantity,
                    items.item_revenue_in_usd,
                    items.item_revenue,
                    items.item_refund_in_usd,
                    items.item_refund,
                    items.coupon,
                    items.affiliation,
                    items.location_id,
                    items.item_list_id,
                    items.item_list_name,
                    items.item_list_index,
                    items.promotion_id,
                    items.promotion_name,
                    items.creatiion_name,
                    items.creation_slot
                    -- items.item_params are used to store the user's custom property of items
                    ${when(config.CUSTOM_ITEM_PARAMS_ARRAY.length > 0,
                        `, ${helpers.generateStructSQL(helpers.generateParamsSQL(
                        config.CUSTOM_ITEM_PARAMS_ARRAY, "items.item_params"))} AS item_params_custom`)}
                )
            FROM UNNEST(items) AS items
            )
        ) AS items,

        -- The standard event params    
        ${helpers.generateStructSQL(helpers.generateParamsSQL(config.CORE_PARAMS_ARRAY))} AS event_params

        -- The custom events params
        ${when(config.CUSTOM_EVENT_PARAMS_ARRAY.length > 0,
            `, ${helpers.generateStructSQL(helpers.generateParamsSQL(
            config.CUSTOM_EVENT_PARAMS_ARRAY))} AS event_params_custom`)}

        -- Add custom user info from user_properties
        -- Custom user info may look like this:
        -- ({name: 'user_type', type: 'string'}, {name: 'subscription_tier', type: 'int'})
        ${when(config.CUSTOM_USER_PROPERTIES_ARRAY.length > 0,
            `, ${helpers.generateStructSQL(helpers.generateParamsSQL(
            config.CUSTOM_USER_PROPERTIES_ARRAY, 'user_properties'))} AS user_properties`)}

        FROM source_ga4_export
),

stage_repack_structs AS (
    SELECT
        * EXCEPT(
            -- These 4 fields are too dirty and need to be cleaned
            ecommerce,
            batch_event_index,
            batch_ordering_id,
            batch_page_id,
        ),

        -- In July 2024 the batch_* parameters were moved to a column. So data before that date should
        -- be found from UNNEST(event_params)
        STRUCT(
            batch_event_index,
            COALESCE(batch_ordering_id, event_params.batch_ordering_id) AS batch_ordering_id,
            COALESCE(batch_page_id, event_params.batch_page_id) AS batch_page_id
        ) as batch,

        -- Repack the ecommerce Struct
        -- Fix transaction_id error by GA4, change to Null if "(not set)". BigQuery would treat "(not set)" as
        -- a order number while Null would be ignored
        -- also remove NANs in ecommerce Struct. Any (100 + NAN) would be NAN, so any single NAN is not allowed
        Struct(
            ecommerce.total_item_quantity,
            IF(IS_NAN(ecommerce.purchase_revenue_in_usd), 0, ecommerce.purchase_revenue_in_usd) AS purchase_revenue_in_usd,
            IF(IS_NAN(ecommerce.purchase_revenue), 0, ecommerce.purchase_revenue) AS purchase_revenue,
            IF(IS_NAN(ecommerce.refund_value), 0, ecommerce.refund_value) AS refund_value,
            IF(IS_NAN(ecommerce.refund_value_in_usd), 0, ecommerce.refund_value_in_usd) AS refund_value_in_usd,
            IF(IS_NAN(ecommerce.shipping_value), 0, ecommerce.shipping_value) AS shipping_value,
            IF(IS_NAN(ecommerce.shipping_value_in_usd), 0, ecommerce.shipping_value_in_usd) AS shipping_value_in_usd,
            IF(IS_NAN(ecommerce.tax_value), 0, ecommerce.tax_value) AS tax_value,
            IF(IS_NAN(ecommerce.tax_value_in_usd), 0, ecommerce.tax_value_in_usd) AS tax_value_in_usd,
            ecommerce.unique_items,
            IF(ecommerce.transaction_id = '(not set)', NULL, ecommerce.transaction_id) AS transaction_id
        ) AS ecommerce,

        FROM stage_unnest_params
),

stage_url_parsing_and_event_id AS (
    SELECT
        *,

        -- The following 3 fields are used to extract standard url params and 
        -- custom url params and click_id from page_location and form 3 sepereate Structs

        -- Standard url parameters from config.js
        -- This is silver layer for the url params so that it would be much easier to use as a structured field
        ${helpers.generateStructSQL(helpers.generateURLParamsSQL(
            config.URL_PARAMS_ARRAY, 'event_params.page_location'
        ))} AS url_params,

        -- Custom url parameters from config.js
        ${when(config.CUSTOM_URL_PARAMS_ARRAY.length > 0,
            `${helpers.generateStructSQL(helpers.generateURLParamsSQL(
                config.CUSTOM_URL_PARAMS_ARRAY, 'event_params.page_location'))}
                AS url_params_custom,`)
        }

        -- click_id from event_params based on config.js
        ${helpers.generateStructSQL(helpers.generateURLParamsSQL(
            config.CLICK_IDS_ARRAY, 'event.params.page_location', false
        ))} AS click_ids,

        -- Create events_id. GA4 raw data does not contain an Event ID (a unique event identifier)
        FARM_FINGERPRINT(
            event_name
            || time.event_timestamp,
            || COALESCE(user_pseudo_id, 'no')
            || COALESCE(event_params.ga_session_id, 0)
            || COALESCE(batch.batch_page_id, 0)
            || COALESCE(batch.batch_ordering_id, 0)
            || COALESCE(batch.batch_event_index, 0)
            || COALESCE(event_params.engagement_time_msec, 0)
        ) AS event_id

    FROM stage_repack_structs
),

stage_discard_synthetic_bundle_events AS (
    -- Discard the system-triggered events which were created by GA4 “Audience Triggers”
    SELECT
        *
    FROM stage_url_parsing_and_event_id
    WHERE (event_params.synthetic_bundle IS NULL or event_params.synthetic_bundle != 1)
),

stage_traffic_source_coalesce_and_click_ids AS (
    SELECT
        * EXCEPT(
            click_ids
        ),

        -- The following code follows the priority order: official fields > event params > URL params
        -- to consolidate them into a single source of truth
        -- Here we directly create a Struct without using helpers.generateStructSQL()
        STRUCT(
            LOWER(COALESCE(collected_traffic_source.manual_campaign_id, IF(batch.batch_ordering_id > 1, NULL, url_params.utm_id))) AS campaign_id,
            LOWER(COALESCE(collected_traffic_source.manual_campaign_name, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.campaign, url_params.utm_campaign)))) AS campaign,
            LOWER(COALESCE(collected_traffic_source.manual_source, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.source, url_params.utm_source)))) AS source,
            LOWER(COALESCE(collected_traffic_source.manual_medium, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.medium, url_params.utm_medium)))) AS medium,
            LOWER(COALESCE(collected_traffic_source.manual_term, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.term, url_params.utm_term)))) AS term,
            LOWER(COALESCE(collected_traffic_source.manual_content, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.content, url_params.utm_content)))) AS content,
            LOWER(COALESCE(collected_traffic_source.manual_source_platform, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.source_platform url_params.utm_source_platform)))) AS source_platform,
            LOWER(COALESCE(collected_traffic_source.manual_creative_format, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.creative_format, url_params.utm_creative_format)))) AS creative_format,
            LOWER(COALESCE(collected_traffic_source.manual_marketing_tactic, IF(batch.batch_ordering_id > 1, NULL, COALESCE(event_params.marketing_tactic, url_params.utm_marketing_tactic)))) AS marketing_tactic
        ) AS fixed_traffic_source,

        STURCT(
            ${config.CLICK_IDS_ARRAY.map(id => helpers.generateClickIdCoalesceSQL(id)).join(", ")}
        ) AS click_ids,

    FROM stage_discard_synthetic_bundle_events
    WHERE event_date >= date_checkpoint
),

-- Fix several attribution error:
-- ad traffic containing gclid is often broken and misclassified by GA4 as organic or referral traffic;
-- traffic coming from the Google app or social media apps may appear as android-app://com... package names;
-- payment redirects such as PayPal, if not excluded, can interrupt the original traffic session.
stage_create_fixed_traffic_source AS (
    SELECT
        * EXCEPT(
            fixed_traffic_source
        ),

        -- Campaign, campaign source & campaign medium should be rewrite if necessary

        STRUCT(
            fixed_traffic_source.campaign_id,

            -- Firstly campaign

            CASE
                WHEN(
                    (COALESCE(fixed_traffic_source.campaign, '') IN ('(organic)', '(referral)', ''))
                    OR fixed_traffic_source.campaign IS NULL
                )
                THEN
                    CASE ${helpers.generateClickCasesSQL(config.CLICK_IDS_ARRAY, "campaign")}
                    -- when the traffic are organic
                    ELSE fixed_traffic_source.campaign
                    END
                -- when the campaign are not from Google Ads 
                ELSE fixed_traffic_source.campaign
            END AS campaign,

            -- Then campaign source


            -- Lastly campaign medium
        
            fixed_traffic_source.term,
            fixed_traffic_source.content,
            fixed_traffic_source.source_platform,
            fixed_traffic_source.creative_format,
            fixed_traffic_source.marketing_tactic
        ) AS fixed_traffic_source
    FROM stage_traffic_source_coalesce_and_click_ids
),

