config {
    type: "incremental",
    description: "Output sessions table with last non direct attribution",
    schema: dataform.projectConfig.vars.OUTPUTS_DATASET,
    tags: ["session","outputs"],
    bigquery: {
        partitionBy: "session_date",
        clusterBy: ["session_id"]
    },
    columns: require("includes/core/documentation/helpers.js").ga4sessions
}

js{
    // It returns the whole js file and needs to find and match helpers object
    const {helpers} = require("includes/core/modules/ga4/helpers.js");
    // It returns the object already so just needs a variable to refer to
    const config = helpers.getModuleConfig("ga4");
    // check if there is invalid columns or duplicate columns in the custom config
    helpers.checkColumnNames(config);
}

pre_operations{
    DECLARE date_checkpoint DATE;
    SET date_checkpoint = {
        ${when(incremental(),
            `SELECT COALESCE(MAX(session_date)+1, DATE('${config.GA4_START_DATE}')) from ${self()}
            where is_final=true`,
            `SELECT DATE('${config.GA4_START_DATE}')`)
        }
    };

    ${when(incremental(),
        `DELETE FROM ${self()} WHERE session_date >= date_checkpoint`)}
}

WITH source_sessions AS (
    SELECT
    FROM ${ref("int_ga4_sessions")}
    WHERE session_date >= date_checkpoint - INTERVAL ${config.LAST_NON_DIRECT_LOOKBACK_DAYS} DAY
    -- Ideally each row in int_ga4_sessions reprensents only one unique session but actually
    -- there might be some duplicates due to the data backfilling, cross-day sessions etc
    -- Keep evety visitor's sessions with the latest end time within lookback days
    QUALIFY ROW_NUMBER() OVER(
        PARTITION BY session_id
        ORDER BY time.session_start_timestamp_utc ASC, time.session_end_timestamp_utc DESC
    ) = 1
),