config {
    type: "incremental",
    description: "Output sessions table with last non direct attribution",
    schema: dataform.projectConfig.vars.OUTPUTS_DATASET,
    tags: ["session","outputs"],
    bigquery: {
        partitionBy: "session_date",
        clusterBy: ["session_id"]
    },
    columns: require("includes/core/documentation/helpers.js").ga4sessions
}

js{
    // It returns the whole js file and needs to find and match helpers object
    const {helpers} = require("includes/core/modules/ga4/helpers.js");
    // It returns the object already so just needs a variable to refer to
    const config = helpers.getModuleConfig("ga4");
    // check if there is invalid columns or duplicate columns in the custom config
    helpers.checkColumnNames(config);
}

pre_operations{
    DECLARE date_checkpoint DATE;
    SET date_checkpoint = {
        ${when(incremental(),
            `SELECT COALESCE(MAX(session_date)+1, DATE('${config.GA4_START_DATE}')) from ${self()}
            where is_final=true`,
            `SELECT DATE('${config.GA4_START_DATE}')`)
        }
    };

    ${when(incremental(),
        `DELETE FROM ${self()} WHERE session_date >= date_checkpoint`)}
}

WITH source_sessions AS (

),