config {
    type: "incremental",
    description: "Output sessions table with last non direct attribution",
    schema: dataform.projectConfig.vars.OUTPUTS_DATASET,
    tags: ["session","outputs"],
    bigquery: {
        partitionBy: "session_date",
        clusterBy: ["session_id"]
    },
    columns: require("includes/core/documentation/helpers.js").ga4Sessions
}

js {
    // It returns the whole js file and needs to find and match helpers object
    const { helpers } = require("includes/core/modules/ga4/helpers.js");
    // It returns the object already so just needs a variable to refer to
    const config = helpers.getModuleConfig("ga4");
    // check if there is invalid columns or duplicate columns in the custom config
    helpers.checkColumnNames(config);
}

pre_operations {
    DECLARE date_checkpoint DATE;
    SET date_checkpoint = (
        ${when(incremental(),
            `SELECT COALESCE(MAX(session_date) + 1, DATE('${config.GA4_START_DATE}')) FROM ${self()}
            WHERE is_final = true`,
            `SELECT DATE('${config.GA4_START_DATE}')`)
        }
    );

    ${when(incremental(), `DELETE FROM ${self()} WHERE session_date >= date_checkpoint`)}
}

WITH source_sessions AS (
    SELECT * FROM ${ref("int_ga4_sessions")}
    WHERE session_date >= date_checkpoint - INTERVAL ${config.LAST_NON_DIRECT_LOOKBACK_DAYS} DAY
    -- Ideally each row in int_ga4_sessions reprensents only one unique session but actually
    -- there might be some duplicates due to the data backfilling, cross-day sessions etc
    
    -- Keep evety visitor's sessions with the latest end time within lookback days
    -- as it is an incremental table so session_date >= date_checkpoint is very needed but also need to
    -- look back for a range of days to find the related sessions
    QUALIFY ROW_NUMBER() OVER(
        PARTITION BY session_id
        ORDER BY time.session_start_timestamp_utc ASC, time.session_end_timestamp_utc DESC
    ) = 1
),

stage_add_last_non_direct AS (
    SELECT
        *,
        IF(
            session_info.is_with_source,
            session_source.first,

            LAST_VALUE(
                IF(
                    COALESCE(
                        session_source.last.campaign_id,
                        session_source.last.campaign,
                        session_source.last.source,
                        session_source.last.medium,
                        session_source.last.term,
                        session_source.last.content,
                        ${helpers.getClickIdsDimensionsSQL(config.CLICK_IDS_ARRAY, 'session_source.last')}
                    ) IS NULL,
                NULL, session_source.last)
            IGNORE NULLS
            ) OVER (
                PARTITION BY user_pseudo_id
                ORDER BY UNIX_MILLIS(time.session_start_timestamp_utc)
                RANGE BETWEEN ${config.LAST_NON_DIRECT_LOOKBACK_DAYS * 24 * 3600 * 1000} PRECEDING AND CURRENT ROW
            )

        ) AS last_non_direct_traffic_source

    FROM source_sessions
),

-- Rewrite NULL default channel grouping to Direct
final_add_direct_to_dcg AS (
    SELECT
        * EXCEPT(session_source)
        REPLACE(
            (
                SELECT AS STRUCT
                    last_non_direct_traffic_source.* EXCEPT(default_channel_grouping),
                    COALESCE(last_non_direct_traffic_source.default_channel_grouping, "Direct") AS default_channel_grouping
            ) AS last_non_direct_traffic_source
        ),
        -- Simplify the session_source Struct so that it is easy to use session_source.source in the reports
        session_source.first AS session_source
    FROM stage_add_last_non_direct
),

-- Do not forget the WHERE clause
-- In CTE stage_add_last_non_direct more data back to LAST_NON_DIRECT_LOOKBACK_DAYS is retrieved in order to find the
-- potential session source so these data should not be written into database and removed here
SELECT * FROM final_add_direct_to_dcg WHERE session_date >= date_checkpoint