config {
    type: "operations",
    schema: dataform.projectConfig.vars.QUALITY_DATASET,
    description: "checking if sessions are valid",
    dependencies: ["assertion_logs", {name:"ga4_sessions"}],
    tags: ["assertions"]
}

js {
    const { helpers } = require("includes/core/helpers");
    const config = helpers.getModuleConfig('ga4');
}

DECLARE assertion STRING DEFAULT 'session validity';
DECLARE check INT64;
DECLARE expectation INT64 DEFAULT 0;
DECLARE sample STRING;
DECLARE assertion_status STRING DEFAULT 'pass';
DECLARE error_msg STRING DEFAULT 'Yippee_ki_yay';

IF ${config.ASSERTIONS_SESSIONS_VALIDITY}
THEN
    SET (check, sample) = (
        SELECT AS STRUCT
            COUNT(*),
            STRING_AGG(CAST(session_id AS STRING), ", " LIMIT 5)
        FROM
            ${ref("ga4_sessions")}
        WHERE
            session_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
        AND (
            (app_info.id IS NOT NULL AND landing_page_location IS NULL)
            OR user_pseudo_id IS NULL
            OR session_id IS NULL
            OR session_date IS NULL
            OR device_category IS NULL
            OR time.session_start_timestamp_utc IS NULL
        )
    );

    IF check > expectations THEN
        SET assertion_status = 'fail';
        SET error_msg = FORMAT("%d sessions not valid. one of these is null: landing_page_location, user_pseudo_id, session_id, session_date, device_category, session_start_timestamp_utc", check);
    END IF;

    INSERT INTO ${ref("assertion_logs")}
    VALUES (
        CURRENT_TIMESTAMP(),
        assertion,
        '${ref("ga4_sessions")}',
        expectations,
        check,
        sample,
        assertion_status,
        error_msg
    );

        -- Use raise using message ... to throw an exception/error
    IF check > expectations THEN RAISE
    USING MESSAGE = error_msg;
    END IF;

END IF;
