config {
    type: "incremental",
    description: "Intermediate incremental sessions table with modeling helpers implmemented. 1 row per session_id. Only valid session",
    schema: dataform.projectConfig.vars.TRANSFORMATION_DATASET,
    tags: ["session","intermediate"],
    dependencies: ["source_categories"],
    bigquery: {
        partitionBy: "session_date",
        clusterBy: ["session_id"]
    }
}

js {
    const { helpers } = require("includes/core/modules/ga4/helpers");
    const config = helpers.getModuleConfig('ga4');
}

pre_operations {
    DECLARE date_checkpoint DATE;
    SET date_checkpoint = (
        ${when(incremental(),
            `SELECT COALESCE(MAX(session_date)+1, DATE('${config.GA4_START_DATE}'))
            FROM ${self()}
            WHERE is_final = true`,
            `SELECT DATE('${config.GA4_START_DATE}')`)}
    );

    ${when(incremental(), `DELETE FROM ${self()} WHERE session_date >= date_checkpoint`)}
}

-- One row for one session
WITH source_events AS (
    SELECT 
        session_id,
        stream_id,
        user_pseudo_id,
        property_id,
        MIN(table_suffix) AS table_suffix, -- Find the earliest date of the session
        COUNT(DISTINCT table_suffix) > 1 as is_multiday_session, -- Check if the session covers more than one day
        MAX(is_final) AS is_final,  -- Return true if session started on an is_final day

        -- All the following info will returned with the first record order by time_stamp acs
        ${helpers.generateArrayAggSQL('device')}, -- device is a Struct in ga4_events
        ${helpers.generateArrayAggSQL('geo')}, -- geo is a Struct in ga4_events
        ${helpers.generateArrayAggSQL('app_info')}, -- app_info is a Struct in ga4_events
        ${helpers.generateArrayAggSQL('platform')},

        -- page is a STRUCT defined in ga4_events
        STRUCT(
            ${helpers.generateArrayAggSQL('page.location', 'landing_page_location')},
            ${helpers.generateArrayAggSQL('page.path', 'landing_page_path')},
            ${helpers.generateArrayAggSQL('page.hostname', 'landing_page_hostname')},
            ${helpers.generateArrayAggSQL('page.referrer', 'landing_page_referrer')},
            ${helpers.generateArrayAggSQL('event_params.content_group', 'landing_content_group')} -- content_group
        ) AS landing_page,

        ${helpers.generateArrayAggSQL('session_traffic_source_last_click')},

        -- Sometimes there is an issue when the Struct is not null, but all its sub-Structs (source, medium,
        -- campaign) are all null, which will make the Dataform believe this Struct is not null but make the attribution 
        -- model fails because all the first/last touch points are null, so we need to make sure that the sub-Struct are not all null)
        
        -- fixed_traffic_source is temparely changed to an Array in order to use ARRAY_AGG() to extract
        -- the first or last value for attribution model
        ${helpers.generateTrafficSourceSQL('fixed_traffic_source', 'first_traffic_source')},
        ${helpers.generateTrafficSourceSQL('fixed_traffic_source', 'last_traffic_source', false)},
        ${helpers.generateClickIdTrafficSourceSQL('click_ids', config.CLICK_IDS_ARRAY, 'first_click_ids')},
        ${helpers.generateClickIdTrafficSourceSQL('click_ids', config.CLICK_IDS_ARRAY, 'last_click_ids', false)},

        -- It is always to retrieve the last user_id because if the user needs to purchase anything, he needs to log in
        -- so the user_id can be identified at that time
        ${helpers.generateArrayAggSQL('user_id', false, false)},

        STRUCT(
            ${helpers.generateArrayAggSQL('page.location', 'exit_page_location', false)},
            ${helpers.generateArrayAggSQL('page.path', 'exit_page_path', false)},
            ${helpers.generateArrayAggSQL('page.hostname', 'exit_page_hostname', false)},
            ${helpers.generateArrayAggSQL('event_params.content_group', 'exit_content_group', false)}
        ) AS exit_page,

        -- ga_session_number stands for the times when the same user visits
        -- Theoriotically all the ga_session_number should be the same in the same session_id, but in BigQuery when there is a
        -- group by clause, all the fields should be in an aggregation funtion
        -- also when MP hits happen, MIN() can help fix it as long as there is a valid value in ga_session_number
        MIN(event_params.ga_session_number) AS ga_session_number,

        MIN(event_date) AS session_date,
        MIN(time.event_timestamp_utc) AS session_start_timestamp_utc,
        MAX(time.event_timestamp_utc) AS session_end_timestamp_utc,
        SUM(event_params.engagement_time_msec) AS engagement_time_msec,

        STRUCT(
            -- As long as user has engaged with the page, event_params.session_engaged = "1"
            LOGICAL_OR(event_params.session_engaged = "1") AS is_engaged_session,
            LOGICAL_OR(has_source) AS is_with_source,
            NOT LOGICAL_OR(has_source) AS is_direct_session,
            LOGICAL_OR(url_params.gtm_debug IS NOT NULL) AS is_debug_session, -- If the session is from test data in GTM preview mode
            LOGICAL_OR(url_params._gl IS NOT NULL) AS is_cross_domain -- If the session is from cross-domain tracking config in GA4
        ) AS session_info,

    FROM ${ref("ga4_events")}

    WHERE
        event_date >= date_checkpoint - 1
    AND
        user_pseudo_id IS NOT NULL
    AND
        session_id IS NOT NULL

    GROUP BY
        session_id,
        stream_id,
        user_pseudo_id,
        property_id
),

source_categories AS (
    SELECT
        source,
        source_category
    FROM ${ref("source_categories")}
),

stage_create_session_source_and_time AS (
    SELECT
        source_events.* EXCEPT(
            -- Move the time-related fields into a single Struct in order to make the reports clean and easy to use
            session_start_timestamp_utc,
            session_end_timestamp_utc,
            engagement_time_msec,
            first_traffic_source,
            last_traffic_source,
            first_click_ids,
            last_click_ids
        ),

        STRUCT(
            source_events.session_start_timestamp_utc,
            source_events.session_end_timestamp_utc,
            source_events.engagement_time_msec,
            TIMESTAMP_DIFF(source_events.session_end_timestamp_utc, source_events.session_start_timestamp_utc,
                SECOND) AS session_duration_s
        ) AS time,

        -- SElECT AS STRUCT() is used because .* is used here which is not allowed in STRUCT()
        -- Finally the data structure here is like:
        -- {"session_source":{"first":{"source", "medium", "campaign", "gclid", "default_channel_grouping"}}, {"last":{}}}
        -- therefore the data analyst can use "select session_source.first.default_channel_grouping from ..."
        (
            SELECT AS STRUCT
                (
                    SELECT AS STRUCT
                        first_traffic_source.*,
                        first_click_ids.*,
                        ${helpers.getDefaultChannelGroupingSQL(config,
                        'first_traffic_source.source',
                        'first_traffic_source.medium',
                        'first_traffic_source.campaign',
                        'join_first.source_category',
                        'first_traffic_source.term',
                        'first_traffic_source.content',
                        'first_traffic_source.campaign_id'
                        )} AS default_channel_grouping
                    ) AS first,

                (
                    SELECT AS STRUCT
                        last_traffic_source.*,
                        last_click_ids.*,
                        ${helpers.getDefaultChannelGroupingSQL(config,
                        'last_traffic_source.source',
                        'last_traffic_source.medium',
                        'last_traffic_source.campaign',
                        'join_last.source_category',
                        'last_traffic_source.term',
                        'last_traffic_source.content',
                        'last_traffic_source.campaign_id'
                        )} AS default_channel_grouping
                    ) AS last
        ) AS session_source

    FROM source_events
    LEFT JOIN source_categories AS join_first
        ON source_events.first_traffic_source LIKE join_first.source
    LEFT JOIN source_categories AS join_last
        ON source_events.last_traffic_source LIKE join_last.source
)

SELECT * EXCEPT(is_multiday_session)
FROM stage_create_session_source_and_time
WHERE (
    session_date >= date_checkpoint -- Do not ask BigQuery to refresh the whole data in ga4_events
    OR
    is_multiday_session -- Some session may cover overnight so this one should be included
)